parameters:
    # Adds a fallback MAILER_USER if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(MAILER_USER): 'example@example.com'

fos_user:
    db_driver: orm
    firewall_name: api
    user_class: App\Entity\User
    from_email:
        address: '%env(MAILER_USER)%'
        sender_name: '%env(MAILER_USER)%'